# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/publicaciones/:title

# Setup
title:            Javier Ojeda
tagline:          'blog'
description:      'My personal blog.'
url:              http://blog.javierojeda.xyz
baseurl:
commentsystem:    google
disqus:           example

author:
  name:           Javier Ojeda
  url:            https://www.linkedin.com/in/javierojedamaldonado/

gems:             [jekyll-paginate]
paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  - icon:         twitter
    url:          https://twitter.com/soy_javierojeda
    desc:         Síguene en Twitter

  - icon:         github
    url:          https://github.com/javierojeda94
    desc:         Check my code

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Javier Ojeda
  url:            http://javierojeda.xyz
  type_title:     Some rights reserved (Forked from http://camporez.github.io)
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
